# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img',
            field=models.ImageField(default='', upload_to='article'),
        ),
    ]
