# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0002_article_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='chopslider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('img', models.ImageField(default='', upload_to='chopslider')),
            ],
        ),
    ]
