# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0003_chopslider'),
    ]

    operations = [
        migrations.AddField(
            model_name='chopslider',
            name='status',
            field=models.CharField(choices=[('d', 'Draft'), ('p', 'Published'), ('w', 'Withdrawn')], default='', max_length=1),
        ),
    ]
