# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0004_chopslider_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chopslider',
            name='enabled',
        ),
        migrations.AlterField(
            model_name='chopslider',
            name='status',
            field=models.CharField(choices=[('d', 'Draft'), ('p', 'Published'), ('w', 'Withdrawn')], default='p', max_length=1),
        ),
    ]
